all:
  children:
    nfs:
      hosts:
        172.31.6.136:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/marion-dev.pem

    webservers:
      hosts:
        172.31.21.47:
          ansible_user: ec2-user
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/marion-dev.pem

    db:
      hosts:
        172.31.1.220:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/marion-dev.pem

    lb:
      hosts:
        172.31.0.71:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /home/ubuntu/.ssh/marion-dev.pem

