pipeline {
    agent any
  
    stages {
        stage('Initial Cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                sh 'echo pass'
                // Uncomment the line below when SCM setup is ready
                 //git branch: 'main', url: 'https://github.com/Maarioon/php-todo2-jk.git'
            }
        }

        stage('Prepare Dependencies') {
            steps {
                sh 'echo pass'
                // Uncomment the lines below to prepare dependencies
                // sh 'mv .env.sample .env'
                // sh 'composer install'
                // sh 'php artisan migrate'
                // sh 'php artisan db:seed'
                // sh 'php artisan key:generate'
            }
        }

        stage('Execute Unit Tests') {
            steps {
                sh 'echo pass'
                // Uncomment the line below to execute unit tests
                // sh '~/vendor/bin/phpunit'
            }
        }

        stage('Code Analysis') {
            steps {
                // Ensure logs directory exists
                sh 'mkdir -p build/logs'
                // Run code analysis
                sh 'phploc app/ --log-csv build/logs/phploc.csv'
            }
        }

        stage('Plot Code Coverage Report') {
            steps {
                script {
                    // Plotting various metrics using PHPLoc CSV output
                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Lines of Code (LOC),Comment Lines of Code (CLOC),Non-Comment Lines of Code (NCLOC),Logical Lines of Code (LLOC)', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'A - Lines of code', yaxis: 'Lines of Code'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Directories,Files,Namespaces', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'B - Structures Containers', yaxis: 'Count'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Average Class Length (LLOC),Average Method Length (LLOC),Average Function Length (LLOC)', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'C - Average Length', yaxis: 'Average Lines of Code'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Cyclomatic Complexity / Lines of Code,Cyclomatic Complexity / Number of Methods ', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'D - Relative Cyclomatic Complexity', yaxis: 'Cyclomatic Complexity'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Classes,Abstract Classes,Concrete Classes', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'E - Types of Classes', yaxis: 'Count'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Methods,Non-Static Methods,Static Methods,Public Methods,Non-Public Methods', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'F - Types of Methods', yaxis: 'Count'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Constants,Global Constants,Class Constants', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'G - Types of Constants', yaxis: 'Count'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Test Classes,Test Methods', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'H - Testing', yaxis: 'Count'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Logical Lines of Code (LLOC),Classes Length (LLOC),Functions Length (LLOC),LLOC outside functions or classes ', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'I - Code Structure by LLOC', yaxis: 'Logical Lines of Code'

                    plot csvFileName: 'plot-code-coverage.csv', 
                        csvSeries: [[displayTableFlag: false, exclusionValues: 'Functions,Named Functions,Anonymous Functions', 
                                    file: 'build/logs/phploc.csv', inclusionFlag: 'INCLUDE_BY_STRING']], 
                        group: 'phploc', numBuilds: '100', style: 'line', title: 'J - Types of Functions', yaxis: 'Count'
                }
            }
        }
    }
}
