pipeline {
    agent any

    stages {
        stage('Code Analysis') {
            steps {
                // Running PHPLoc for code analysis
                sh 'phploc app/ --log-csv build/logs/phploc.csv'
            }
        }

        stage('Plot Code Coverage Report') {
            steps {
                script {
                    // Plotting code metrics using the generated CSV from PHPLoc
                    def csvFile = 'build/logs/phploc.csv'

                    plot csvFileName: 'plot-loc.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Lines of Code (LOC),Comment Lines of Code (CLOC),Non-Comment Lines of Code (NCLOC),Logical Lines of Code (LLOC)', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'A - Lines of Code', 
                         yaxis: 'Lines of Code'

                    plot csvFileName: 'plot-structures.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Directories,Files,Namespaces', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'B - Structures Containers', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-average-length.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Average Class Length (LLOC),Average Method Length (LLOC),Average Function Length (LLOC)', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'C - Average Length', 
                         yaxis: 'Average Lines of Code'

                    plot csvFileName: 'plot-complexity.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Cyclomatic Complexity / Lines of Code,Cyclomatic Complexity / Number of Methods', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'D - Relative Cyclomatic Complexity', 
                         yaxis: 'Cyclomatic Complexity by Structure'

                    plot csvFileName: 'plot-class-types.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Classes,Abstract Classes,Concrete Classes', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'E - Types of Classes', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-method-types.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Methods,Non-Static Methods,Static Methods,Public Methods,Non-Public Methods', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'F - Types of Methods', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-constants.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Constants,Global Constants,Class Constants', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'G - Types of Constants', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-testing.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Test Classes,Test Methods', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'H - Testing', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-code-structure.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Logical Lines of Code (LLOC),Classes Length (LLOC),Functions Length (LLOC),LLOC outside functions or classes', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'I - Code Structure by Logical Lines of Code', 
                         yaxis: 'Logical Lines of Code'

                    plot csvFileName: 'plot-function-types.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Functions,Named Functions,Anonymous Functions', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'J - Types of Functions', 
                         yaxis: 'Count'

                    plot csvFileName: 'plot-structure-objects.csv',
                         csvSeries: [[displayTableFlag: false, 
                                      exclusionValues: 'Interfaces,Traits,Classes,Methods,Functions,Constants', 
                                      file: csvFile, 
                                      inclusionFlag: 'INCLUDE_BY_STRING', 
                                      url: '']], 
                         group: 'phploc', 
                         numBuilds: '100', 
                         style: 'line', 
                         title: 'K - Structure Objects', 
                         yaxis: 'Count'
                }
            }
        }
    }
}
