---
- name: Include dynamic variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always
  
- name: Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- import_playbook: ../static-assignments/artifactory.yml
  tags:
    - artifactory


